//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.ServicesUsed = new HashSet<ServicesUsed>();
        }
    
        public int BookingId { get; set; }
        public System.DateTime BookingDate { get; set; }
        public int StayDuration { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public int BookingAmount { get; set; }
        public int HotelId { get; set; }
        public int EmployeeId { get; set; }
        public int GuestId { get; set; }
        public Nullable<int> DiscountId { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicesUsed> ServicesUsed { get; set; }
        public virtual Discount Discount { get; set; }
        public virtual Employees1 Employees1 { get; set; }
        public virtual Guests Guests { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
