//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelsApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProHotelEntities : DbContext
    {
        public ProHotelEntities()
            : base("name=ProHotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Booking> Booking { get; set; }
        public virtual DbSet<Discount> Discount { get; set; }
        public virtual DbSet<Addresses> Addresses { get; set; }
        public virtual DbSet<Amenities> Amenities { get; set; }
        public virtual DbSet<Bookings> Bookings { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Discounts> Discounts { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Hotels> Hotels { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<RoomTypes> RoomTypes { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Employees1> Employees1 { get; set; }
        public virtual DbSet<Guests> Guests { get; set; }
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<ServicesUsed> ServicesUsed { get; set; }
    }
}
