//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int LoginId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string SecurityQuestion { get; set; }
        public string Answer { get; set; }
        public int HotelId { get; set; }
        public string NewUser { get; set; }
    
        public virtual Employees1 Employees1 { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
