//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesUsed
    {
        public int ServicesUserId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public int BookingId { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Services Services { get; set; }
    }
}
